### ISSUE TITLE
请问有原理图吗？

### ISSUE THREAD

**Issue by 1304963427** [zengcym/HDMI-To-MIPI#1]
请问有原理图吗？哪怕放个PDF原理图参考也行啊

**Comment by epikao** [comment]
@zengcym , I would also be interested in the scheme, and would also pay something for it...

**Comment by zengcym** [comment]
I'm sorry, I didn't follow the process to process the PCB, I don't have the scheme, please refer to this [[link](https://github.com/peng-zhihui/HDMI-PI)]I just added another DAC audio part.
