### ISSUE TITLE
Development

### ISSUE THREAD

**Issue by craipe** [zengcym/HDMI-To-MIPI#2]
Hi friend. Can I ask you to share a project? I want to create a tablet on CM 4, but I can't find the correct circuit and trace of this board anywhere on the Internet, I found only Gerber files from you. I would be very grateful for your help. I can pay if required. If it doesn't bother you, export the project to Easy E DA PRO so that I can install it for myself.

嗨，朋友。 我可以请你分享一个项目吗? 我想在CM4上创建一个平板电脑，但我在互联网上的任何地方都找不到这个板的正确电路和痕迹，我只从你那里找到了Gerber文件。 我将非常感谢你的帮助。 如果需要，我可以付钱。 如果它不打扰您，请将项目导出到EasyEDA PRO，以便我可以自己安装它。

**Comment by zengcym** [comment]
I'm not sure what you need, can you be specific？

**Comment by oleqlazyrin** [comment]
> I'm not sure what you need, can you be specific？

I ask you to share the source data of the project so that I can implement it into my board. You have only Gerber files presented here.

**Comment by zengcym** [comment]
Sorry, I use Mentor software to process the file, it is already in the shared document. You can do some conversion work yourself.
